{% set name = "pickleDB" %}
{% set version = "1.3.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | lower }}-{{ version }}.tar.gz
  sha256: b5cdc3bc9a7a6dbf7c5bbb81191f2ee9981ff4b947ed1f423e880566a5dda2c9

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - pickledb

about:
  home: http://github.com/patx/pickledb
  license: BSD 3-clause
  license_family: BSD
  # See https://github.com/patx/pickledb/issues/52
  license_file: LICENSE
  summary: A lightweight and simple database using json.

extra:
  recipe-maintainers:
    - xhochy
