{% set name = "pickleDB" %}
{% set version = "1.1.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8b49cca3c06c4e92bdfcda6c589067cdc1e0184612af42c95633d4ffc41438e6

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - pickledb

about:
  home: http://github.com/patx/pickledb
  license: BSD 3-clause
  license_family: BSD
  # See https://github.com/patx/pickledb/issues/52
  license_file: LICENSE
  summary: A lightweight and simple database using json.

extra:
  recipe-maintainers:
    - xhochy
