{% set name = "pickleDB" %}
{% set version = "1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.lower() }}-{{ version }}.tar.gz
  sha256: b2ebaec7e9c0e8dccafffbb909747bfa3c2d02ea6c24d238c82a94f49052bc48

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - pickledb

about:
  home: http://github.com/patx/pickledb
  license: BSD 3-clause
  license_family: BSD
  # See https://github.com/patx/pickledb/issues/52
  license_file: LICENSE
  summary: A lightweight and simple database using json.

extra:
  recipe-maintainers:
    - xhochy
