travis:
  secure:
    BINSTAR_TOKEN: XS3ZlcSf5/bX9mPL4TeqLvLLlFlEnwQf1Uynf0HSZqQtIfLwpHrZBIm2zHOs7VLOG8wvStxSPXcchM39QL9eWK+qQiex6MsRImWZB6eHlvNCeVzsbFj8zq3cBh/YEc64YTFgd83/VR+4icAHNytseGteaAbgGlxLZ1kSgAFGJx3e4Aebl1EIruKtmOFEJQZb+UZ39B2OvT2zD2FLvDRllqCtzMTbcAnsDme6oiEVEe8FByU6N6ytsTT8/lzJWPzs+s2+gDyjsPvR3R+BenBdMViCTZH2pDc0LSgDKcig4O2xTYDyKQt/cLLiuZ10Z0MnQ6fBIb5kqreqT1FuHbTZx+0424lnaYFCsoj5U4mNzTMrjdxKnswD7bz+Qb8Qzz+Z0d5XftDgRZmhnOE5VX7pw+T/iOIZEBQ2wsSsXyukCCMDwQ4u9cv9VR0BCeZ26X+A/7OFZzJ7+qFNzXh6NurLB2ZaaWSIfsL982Vycbz7xW2+2cP3pCXnSOuZgNaSZBnDbMNFA35VjPrFqYi42aCaDFvkX6oVAsTCnVaF2EDbGA8X5ACkomy+HFEEGQXJ2jum4fBdKpKwgp0uyFlOslPX7YZrTMYaiAQonmOyEd2N/qcU4AV4jmr2nKO320fgigJUFrqVvmE5vG1WAsItDLxm5CA3AoYkRansx9ylwVnV9UQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
